GET https://bcn-fem-tech-http-store-dani.herokuapp.com/products
Accept: application/json

###
POST https://bcn-fem-tech-http-store-dani.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=melon&price=7

###

